name: ludo_test
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  provider:
  equatable:
  flutter:
    sdk: flutter
  firebase_core: ^1.20.0
  firebase_auth: ^3.6.2
  cloud_firestore: ^3.4.3
  socket_io_client: ^1.0.2

dev_dependencies:
  flutter_lints: ^1.0.0
  lints: any
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
